name: Web Triggered Workflow

on:
  repository_dispatch:
    types: [web_trigger]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: |
          echo "Triggered from GitHub Pages"
          echo "Date: ${{ github.event.client_payload.date }}"
          echo "Receipt: ${{ github.event.client_payload.receipt }}"
